Database/230412/230412offline/pjt_example/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    # 댓글관련 CRUD : 읽는거랑, 수정은 필요없을 거 같고..
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

Database/230412/230412offline/pjt_example/articles/models.py
from django.db import models
# 모델에서는 아래 방법은 쓰지 않습니다.
# from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name='articles')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_articles')
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content

Database/230412/230412offline/pjt_example/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ('user', 'like_users',)

class CommentForm(forms.ModelForm):
    class Meta:
        model  = Comment
        # fields = '__all__'
        exclude = ('article',)

Database/230412/230412offline/pjt_example/articles/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe

from .models import Article, Comment
from .forms import ArticleForm, CommentForm


# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


#사용자가 로그인 한 경우에만 접근할 수 있도록 허용
@login_required
@require_safe
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    #댓글 조회후에 context에 추가 
    comments = article.comments.all()
    context = {
        'article': article,
        'comment_form' : comment_form,
        'comments' : comments
    }
    return render(request, 'articles/detail.html', context)


@login_required
@require_http_methods(['GET','POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()

    context = {'form': form}
    return render(request, 'articles/create.html', context)

# @login_required
@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        # 게시글 작성자와 현재 로그인된 사용자가 다른데, 삭제가 된다.
        # 게시글 작성자와 로그인된 사용자가 같으면 삭제하도록 변경
        article = Article.objects.get(pk=pk)
        if article.user == request.user:
            article.delete()
    return redirect('articles:index')

@login_required
@require_http_methods(['GET','POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', pk=article.pk)
        else:
            form = ArticleForm(instance=article)

        context = {'form': form, 'article': article}
        return render(request, 'articles/update.html', context)
    else:
        return redirect('articles:index')

@require_POST
def comment_create(request,article_pk):
    if request.user.is_authenticated:
        # 댓글저장하고, 상세화면으로 넘겨주기
        article = Article.objects.get(pk = article_pk)
        comment_form = CommentForm(request.POST)
        # Comment.object.create(content ='test', article=article)
        # comment_form.article = article
        # comment.article
        if comment_form.is_valid():
            comment = comment_form.save(commit=False) #DB에 저장은 안되는데...comment 객체는 돌려줍니다.
            comment.article = article
            comment.save()
        return redirect('articles:detail',article_pk)
    return redirect('accounts:login')
    
@require_POST
def comment_delete(request,article_pk,comment_pk):
    if request.user.is_authenticated:
        # 댓글 삭제하고...게시글 상세화면으로 돌아가기
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        return redirect('articles:detail', article_pk)
    return redirect('accounts:login')

@login_required 
@require_POST
def likes(request,article_pk):
    # 현재 로그인한 사람이 게시글에 좋아요를 누르고 있는거에요...
    # article_pk 에 해당하는 게시글의 좋아요 목록에 로그인한 사람을 추가 하거나
    # 이미 있다면 삭제 (좋아요 취소)
    article = Article.objects.get(pk = article_pk)
    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:detail', article_pk)



    

Database/230412/230412offline/pjt_example/articles/templates/articles/create.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글작성</h1>
  <hr />

  <form
    action="{% url 'articles:create' %}"
    method="POST"
    enctype="multipart/form-data">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="작성하기"/>
  </form>

  <br />
  <hr>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

Database/230412/230412offline/pjt_example/articles/templates/articles/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  <hr />

  {% if article.image %}
    <img src="{{article.image.url}}" />
  {% endif %}

  <div id="article-content">
    <p>작성자 : <a href="{% url 'accounts:profile' article.user.username %}">{{article.user}}</a> </p>
    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <p>생성시각 : {{article.created_at}}</p>
    <p>수정시각 : {{article.updated_at}}</p>

    <hr>
    <form action="{% url 'articles:likes' article.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in article.like_users.all %}
        <input type="submit" value="좋아요 취소">
      {% else %}
        <input type="submit" value="좋아요">
      {% endif %}
    </form>
    <p>{{ article.like_users.all|length }} 명이 좋아합니다.</p>
    <hr>
    <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value="댓글 작성">
    </form>
    <p>{{ comments|length}} 개의 댓글이 있습니다.</p>
    <ul>
      {% for comment in comments  %}
        <li>{{ comment.content}} 
          <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
          </form></li> 
      {% empty %}
          <p> 댓글이 없어요....</p>
      {% endfor %}
      
    </ul>
    <hr>
    {% if article.user == request.user %}
      <a href="{% url 'articles:update' article.pk %}">수정하기</a>
      <form action="{% url 'articles:delete' article.pk %}" id="delete-form">
        {% csrf_token %}
        <input type="submit" value="삭제하기" id="delete-btn" />
      </form><br>
      <hr>
    {% endif %}
    <a href="{% url 'articles:index' %}">목록보기</a>
  </div>
{% endblock content %}

Database/230412/230412offline/pjt_example/articles/templates/articles/index.html
{% extends 'base.html' %} 

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:create' %}">작성하기</a>
  <hr />

  {% for article in articles %}
    <p>
      [{{article.id}}] <a href="{% url 'articles:detail' article.pk %}" id="article-title">{{article.title}}</a>
    </p>
    <hr />
  {% endfor %} 

{% endblock content %}